### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by suggested-username** [Jibble330/DuolingoStoryBot#1]
I'm running using python since the exe didn't give me the logs. it stopped doing nothing

`C:\Users\Administrator\Downloads\DuolingoStoryBot-main\DuolingoStoryBot-main>python  DuolingoStoryBot.py
C:\Users\Administrator\Downloads\DuolingoStoryBot-main\DuolingoStoryBot-main\DuolingoStoryBot.py:266: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(main())
Run in background? (y/n): y
Xp amount to terminate after: 2000
`

**Comment by suggested-username** [comment]
Hi. your update makes it possible to see some progress. The chromium opens up. But it can't login with user and password. I already double checked it, but still no joy. I can login with google account, but it stuck there and doing nothing

/Users/valsze/Downloads/DuolingoStoryBot-main/DuolingoStoryBot.py:281: DeprecationWarning: There is no current event loop<br>
  asyncio.get_event_loop().run_until_complete(main())<br>
Run in background? (y/n): n<br>
Xp amount to terminate after: 2000<br>
Traceback (most recent call last):<br>
  File "/Users/valsze/Downloads/DuolingoStoryBot-main/DuolingoStoryBot.py", line 281, in <module>
    asyncio.get_event_loop().run_until_complete(main())<br>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete<br>
    return future.result()<br>
           ^^^^^^^^^^^^^^^<br>
  File "/Users/valsze/Downloads/DuolingoStoryBot-main/DuolingoStoryBot.py", line 275, in main<br>
    await login() #Login with provided credientials<br>
    ^^^^^^^^^^^^^<br>
  File "/Users/valsze/Downloads/DuolingoStoryBot-main/DuolingoStoryBot.py", line 84, in login<br>
    await page.waitForSelector('div[data-test="skill"]', {'timeout': 60000})<br>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyppeteer/frame_manager.py", line 855, in __await__
    raise result<br>
pyppeteer.errors.TimeoutError: Waiting for selector "div[data-test="skill"]" failed: timeout 90000ms exceeds.
